cirruslabs/packer-plugin-tart

- builder/tart/builder.go
- builder/tart/builder.hcl2spec.go
- builder/tart/step_run.go
- docs/builders/tart.mdx
> Add headless option

- go.mod
- go.sum
`github.com/zclconf/go-cty` package [introduced a breaking change in it's `1.11.0` release](https://github.com/zclconf/go-cty/commit/97bafac0dea33a3f74db88ab54dea2937b9e8aef) which breaks communication with endpoints using older versions of that package, namely, Packer: https://github.com/hashicorp/packer/pull/11954.
If you will try to build `packer-plugin-tart` manually and use it, the following exception will be thrown:
```
2022/09/15 09:42:07 packer-plugin-tart plugin: 2022/09/15 09:42:07 Waiting for connection...
2022/09/15 09:42:07 Received unix RPC address for /Users/edi/.packer.d/plugins/packer-plugin-tart: addr is /var/folders/tg/9y32_b7x4_sgg69j691gq_wh0000gn/T/packer-plugin1520519980
2022/09/15 09:42:07 packer-plugin-tart plugin: 2022/09/15 09:42:07 Serving a plugin …
```
> Downgrade github.com/zclconf/go-cty to 1.10.0

- .github/workflows/release.yml
[`Cmd.Environ()`](https://pkg.go.dev/os/exec@master#Cmd.Environ) was only [added in Golang 1.19](https://tip.golang.org/doc/go1.19).
@fkorotkov please re-create the `v0.5.0` tag too as the build had failed.
> Bump Golang to 1.19

- go.mod
The [Environ() function](https://pkg.go.dev/os/exec@go1.19.2#Cmd.Environ) was implemented in go 1.19, this bumps the module required version to match.
https://github.com/cirruslabs/packer-plugin-tart/blame/d0187878700616ab5178124ecf74b8c77951e826/builder/tart/step_run.go#L49
> Bump to go 1.19

- .gitignore
- builder/tart/builder.go
- builder/tart/builder.hcl2spec.go
- builder/tart/step_create_linux_vm.go
- builder/tart/step_disk_resize.go
- builder/tart/step_run.go
- example/ubuntu-22.04-hello.pkr.hcl
- example/ubuntu-22.04-prepare.sh
- example/ubuntu-22.04-vanilla.pkr.hcl
Resolves #32
I'm new to packer, go & provisioning in general so things might be ill formed but the example works.
Used https://ubuntu.com/server/docs/install/autoinstall-quickstart as a starting point for auto install.
A few notes:
It assumes the install process will shutdown the VM rather than restart it at the end of installation: the sample ubuntu autoinstall will just loop into the installer if the system is restarted rather than shutdown.
The auto-resize in the guest OS is probably less generic than the macOS one so ~~a `resize_disk_command` was introduced.~~ fixing the disk size is left to the user with generic shell provisioning steps.
The `boot_command` is hijacked to be used for the VM creation/installation rather than the following run.
> Add support for linux VMs

- builder/tart/builder.go
- builder/tart/builder.hcl2spec.go
- builder/tart/step_create_linux_vm.go
- docs/builders/tart.mdx
- example/install_rosetta.sh
- example/ubuntu-22.04-rosetta.pkr.hcl
- version/version.go
Rosetta support was added in [tart 0.35.0](https://github.com/cirruslabs/tart/releases/tag/0.35.0). This PR makes this feature available in the packer plugin and fixes https://github.com/cirruslabs/packer-plugin-tart/issues/41
> Add rosetta support for Linux guest VMs

- builder/tart/step_run.go
- version/version.go
Version 0.6.2 added Rosetta Support on VMs creation. This PR enables Packer to attach rosetta on existing VMs
> Added Rosseta support for existing Linux VMs

- builder/tart/builder.go
- builder/tart/builder.hcl2spec.go
- builder/tart/step_run.go
- go.mod
- go.sum
Resolves https://github.com/cirruslabs/packer-plugin-tart/issues/29.
> HTTP server support

- builder/tart/builder.go
- builder/tart/builder.hcl2spec.go
- builder/tart/step_clone_vm.go
- docs/builders/tart.mdx
Adds the ability to do `allow_insecure = true` to add `--insecure` to `tart clone` command.
> Add `allow_insecure` flag for pulling from insecure repositories

- builder/tart/builder.go
- builder/tart/step_run.go
Currently the `boot_wait` command does not do anything, even though it is [documented](https://developer.hashicorp.com/packer/plugins/builders/tart#boot_wait) as "The time to wait after booting the initial virtual machine before typing the boot_command".
Currently the workaround I have been using is to add `<wait90s>` in the `boot_command`, which works but makes the config a little harder to follow.
It seems this was caused as the boot wait was not currently implemented fully, so this PR adds this functionality.
For example, setting `boot_wait = "90s"` will now produce:
```
==> tart-cli.vm: Starting the virtual machine...
==> tart-cli.vm: Waiting for the VNC server credentials from Tart...
==> tart-cli.vm: Retrieved VNC credentials, connecting...
==> tart-cli.vm: Connected to the VNC!
==> …
```
> Respect boot_wait for VNC

- builder/tart/builder.go
The boot_command should also be interpolated. Otherwise, the following packer will fail with an error:
```
{
"builders": [
{
"type": "tart-cli",
"name": "vm-macos12-arm64:packer-base-tart",
"vm_name": "vm-macos12-x64-packer-base-tart-currently-building{{user `tart_suffix`}}",
"headless": false,
"from_ipsw": "https://updates.cdn-apple.com/2022FallFCS/fullrestores/012-40537/0EC7C669-13E9-49FB-BD64-9EECC1D174B2/UniversalMac_12.6_21G115_Restore.ipsw",
"cpu_count": 2,
"memory_gb": 4,
"boot_wait": "3m",
"recovery": true,
"boot_command": [
"<wait60s><right><right><enter>",
"<wait10s><enter>",
"<wait10s><leftCtrlOn><f2><leftCtrlOff>",
"<right><right><right><right><down><down><down><enter>",
"<wait10s>",
"diskutil eraseDisk JHFS+ 'Macintosh HD' disk0<enter>",
"<wait5s>",
"curl -o …
```
> Don't filter out boot_command in interpolate

- builder/tart/builder.go
...and initialize the interpolation context properly.
With this PR, both of the examples work:
```hcl
source "tart-cli" "tart" {
vm_base_name   = "macos"
vm_name        = "packer"
http_directory = "/tmp/"
boot_command   = [
"<wait15s>{{ .HTTPIP }} {{ .HTTPPort }}<wait60s>",
]
ssh_username   = "admin"
ssh_password   = "admin"
}
build {
sources = ["source.tart-cli.tart"]
}
```
```json
{
"builders": [
{
"type": "tart-cli",
"name": "user-variable-test",
"vm_base_name": "ghcr.io/cirruslabs/macos-ventura-base:latest",
"vm_name": "user-variable-test-vm",
"headless": false,
"boot_command": [
"{{user `some_variable`}}"
],
"ssh_username": "admin",
"ssh_password": "admin"
}
],
"variables": {
"some_variable": "some value"
}
}
```
Resolves #99.
> Don't interpolate boot_command too early

- .web-docs/README.md
- docs/README.md
This change updates the links to the plugin components on the main integration [index page](https://developer.hashicorp.com/packer/integrations/cirruslabs/tart), with the correct URL structure. Integration links now take the following URL format
`/packer/integrations/org-name/plugin-name/latest/components/type/name`. 
After merging please trigger a manual notify integration release job with the latest plugin version to refresh the integration portal. Otherwise, the links will remain broken until the next official plugin release.
> docs/README.md: Fix broken plugin links on integration portal

- builder/tart/diskutil_parser.go
- builder/tart/diskutil_parser_test.go
...but only if there's a single disk that has the last partition formatted as `Apple_APFS`.
Resolves https://github.com/cirruslabs/packer-plugin-tart/issues/112.
> ParseDiskUtilPlistOutput: allow multiple disks to be present

- builder/tart/step_run.go
Simple change to provide PACKER_HTTP_ADDRESS & PACKER_HTTP_IP to the provisioner scripts.
fixes: #117
> Added http_ip to provide PACKER_HTTP_ADDRESS to the provisioner scripts

- builder/tart/step_run.go
Following VMX driver practices - allowing user to see the VNC password for debugging purposes. It should not be a security concern, because such password is autogenerated during the image build.
Looks like that:
```
==> tart-cli: Waiting for the VNC server credentials from Tart...
==> tart-cli: Retrieved VNC credentials, connecting...
tart-cli: If you want to view the screen of the VM, connect via VNC with the password "thumb-genre-width-motion" to
tart-cli: vnc://127.0.0.1:60612
==> tart-cli: Connected to the VNC!
```
fixes: #114
> Added notification for user about located VNC password & address

- builder/tart/builder.go
- builder/tart/step_cleanup.go
- builder/tart/step_clone_vm.go
> Cleanup VM in case of a failure

- builder/tart/step_run.go
We do `sudo -S shutdown -h now` to gracefully shut down during
cleanup, but the -S flag to sudo results in the prompt being
written to stderr, which results in scary looking red text
in the Packer log. Pass a custom empty prompt to silence it.
> Disable password prompt during cleanup shutdown

- builder/tart/helpers.go
- builder/tart/ssh.go
- builder/tart/step_cleanup.go
- builder/tart/step_clone_vm.go
- builder/tart/step_create_linux_vm.go
- builder/tart/step_create_vm.go
- builder/tart/step_set_vm.go
Creating a Tart VM may involve long running operations such as downloading an IPSW, or installing the OS. Tart gives us progress during these operations, so let's forward it to the Packer UI, the same way the shell-local provisioner does.
If a packer.Ui is not provided, we keep the previous code path that returns the output to the caller, for example used by the TartMachineIP helper.
> Stream Tart stdout/stderr output to Packer UI

- builder/tart/builder.go
- builder/tart/step_run.go
Without a communicator we can't provision, and if we don't have
boot commands there's not any keys to send to the running VM, so
running it is not needed.
This allows configuring builders that only create the VM,
in preparation for later OS installation and provisioning:
```hcl
source "tart-cli" "create-only" {
cpu_count    = 4
memory_gb    = 8
disk_size_gb = 40
from_ipsw    = var.ipsw_file
vm_name      = "pre-install-vm"
communicator = "none"
}
```
Also, there's no need to connect to VNC if we have no boot commands
to type.
> Skip unneeded steps

- GNUmakefile
- version/version.go
With modern Packer, and Packer templates with required_plugins sections, the plugins need to follow a specific folder structure and also come with a sha256 hash of the plugin.
By using `packer plugins install --path` we can let Packer deal with the specifics of installing a plugin from disk instead of from a repository.
> Use packer plugins install --path to install (development version)

- builder/tart/helpers.go
localexec.RunAndStream does its own logging of the command and arguments, so we only need to do so ourselves if we're running the command manually.
> Avoid duplicated logging by TartExec

- .github/workflows/release.yml
- go.mod
To prevent the build from failing: https://github.com/cirruslabs/packer-plugin-tart/actions/runs/8544633665/job/23411110919.
> .github/workflows/release.yml: use Golang 1.22

- builder/tart/recoverypartition/delete.go
- builder/tart/recoverypartition/delete_test.go
I'm not sure how it even worked before, because this effectively is a no-op:
https://github.com/cirruslabs/packer-plugin-tart/blob/42fc7fe3650e65a5f46cf0cc58643707edd2cd98/builder/tart/recoverypartition/delete.go#L39-L41
See also https://github.com/cirruslabs/packer-plugin-tart/pull/141#issuecomment-2034991591.
> Fix recoverypartition.Delete() and add a test

- builder/tart/diskutil_parser.go
- builder/tart/diskutil_parser_test.go
Otherwise `recovery_partition = "keep"` wouldn't work.
> ParseDiskUtilPlistOutput: relax the requirements w.r.t. last partition

- .goreleaser.yml
- GNUmakefile
- version/version.go
The go-gitver package looks at the git describe output and resolves a version based on that.
If the git describe is a plain tag, the resulting plugin version matches the tag.
If there are commits on top of the most recent tag, or the working directory is dirty, the resulting plugin version is the latest plugin version with the patch version bumped, and the "dev" suffix added.
The same logic has been applied to the goreleaser file, so that the releasing logic can be tested with --snapshot
> Generate plugin version at build time based on git describe

- README.md
- docs/README.md
Hi!
I've fixed the typo on the `https://developer.hashicorp.com/packer/integrations/cirruslabs/tart`:
<details>
<summary>Screenshot:</summary>
</details>
Also, I've updated the example versions of the plugin in the docs: `0.6.0 => 1.11.1`
> Docs: update instructions on the Packer website and use newer version as an example configuration

- .web-docs/README.md
I'm not sure why the `ensure-docs-compiled.yaml` workflow didn't run on https://github.com/cirruslabs/packer-plugin-tart/pull/150, but we have to do this every time we change the docs now.
> $ make generate

- builder/tart/step_disk_file_prepare.go
Resolves https://github.com/cirruslabs/packer-plugin-tart/issues/149.
> (*stepDiskFilePrepare).Run(): add a missing fallthrough statement

- builder/tart/builder.go
To load the `ssh_private_key_file` when specified.
Resolves https://github.com/cirruslabs/packer-plugin-tart/issues/162.
> Use SSH key generation step

- .web-docs/components/builder/tart/README.md
- builder/tart/builder.go
- builder/tart/builder.hcl2spec.go
- builder/tart/step_clone_vm.go
- docs/builders/tart.mdx
To always have an up-to-date image before building.
Resolves https://github.com/cirruslabs/packer-plugin-tart/issues/171.
> Introduce "always_pull" option

- .web-docs/components/builder/tart/README.md
- builder/tart/step_run.go
- builder/tart/vnc.go
- builder/tart/vnc.mm
- docs/builders/tart.mdx
Using `<wait "string">` or `<wait "(some|regex|here)">` allows installing macOS without having to specify hard-coded timeout waits such as `<wait10s>`.
> Add custom boot command that waits for text to appear
